pages:
  stage: deploy
  script:
    # No script is needed as the HTML/CSS is already generated.
    - echo "Deploying GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main  # or the branch you want to deploy from
